# This file was generated by GoReleaser. DO NOT EDIT.
cask "mewsh" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "cc64a4a3714036b1a742de2daf2b3a9e0fe9050e99147499da42b50e30027b34"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "d10eab730a4e466a983e908e8a0cbc766688c186a1d6608fc11fbeffbcb0c06f"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e1a894fe2bc19e2dceee5997227d8c1712f88bb55d1891f78848b46601ee86a"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "492f028a7c2a0f4c287803b506bc369c4d6d73cc881048f5fc4d2bd03e94b46c"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  name "mewsh"
  desc "SSH profile manager with CLI and TUI"
  homepage "https://github.com/mewisme/mewsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mewsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mewsh"]
    end
  end

  # No zap stanza required

end
