# This file was generated by GoReleaser. DO NOT EDIT.
cask "mewsh" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "d0e4327d786972802b4cf689d6053a8ff531d030319915e84066a9a1afea7777"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "ee0d133724b6c235a16ac3ff5639c3860527059ddf060a5f241e891b06acd04a"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  on_linux do
    on_intel do
      sha256 "efb6eed27d5bb02a7c1ad8e17a35a7240e17985d78667f0974c495b411445297"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "31b942746f01314a6c92b527f994f00055dce2a3d7f43b704a6ef2c41b6e72bc"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  name "mewsh"
  desc "SSH profile manager with CLI and TUI"
  homepage "https://github.com/mewisme/mewsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mewsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mewsh"]
    end
  end

  # No zap stanza required

end
