# This file was generated by GoReleaser. DO NOT EDIT.
cask "mewsh" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "6c5c430e7781bc71b33453fde99aba1509ca52298d1845e603c222284328f618"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "c2e08c26d69050369755509c7ef993a37cbda853d4a383cd3ed29022d0a3ca81"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  on_linux do
    on_intel do
      sha256 "365e5047ba84f75220ba8b7b8b7bf8e060bcaff6d366eff057129c7b1e98d877"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
    on_arm do
      sha256 "1f7820a51ef4b9db384a7e318578a0a4004501242a54381e1b35c8cd66b77ec1"
      url "https://github.com/mewisme/mewsh/releases/download/v#{version}/mewsh_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mewisme/mewsh"
    end
  end

  name "mewsh"
  desc "SSH profile manager with CLI and TUI"
  homepage "https://github.com/mewisme/mewsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mewsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mewsh"]
    end
  end

  # No zap stanza required

end
